# Generated by Django 6.1.1 on 2026-09-25 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='issues/')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_recurring', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('verified', 'Verified'), ('authority_identified', 'Authority Identified'), ('reported_to_authority', 'Reported to Authority'), ('followup_required', 'Follow-up Required'), ('action_taken', 'Action Taken'), ('community_verified', 'Community Verification'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('no_action', 'No Action')], default='reported', max_length=30)),
                ('responsible_authority_category', models.CharField(blank=True, max_length=150)),
                ('supporter_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(limit_choices_to={'category_type': 'issue'}, on_delete=django.db.models.deletion.PROTECT, to='core.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.location')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('verified', 'Verified'), ('authority_identified', 'Authority Identified'), ('reported_to_authority', 'Reported to Authority'), ('followup_required', 'Follow-up Required'), ('action_taken', 'Action Taken'), ('community_verified', 'Community Verification'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('no_action', 'No Action')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='issue_updates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='issues.issue')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status'], name='issues_issu_status_003ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['-created_at'], name='issues_issu_created_c92651_idx'),
        ),
    ]
