# Generated by Django 6.1.1 on 2026-09-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, help_text='Blank = platform-wide', max_length=100)),
                ('trees_planted', models.PositiveIntegerField(default=0)),
                ('trees_survived', models.PositiveIntegerField(default=0)),
                ('cleanup_drives', models.PositiveIntegerField(default=0)),
                ('waste_collected_kg', models.PositiveIntegerField(default=0)),
                ('active_volunteers', models.PositiveIntegerField(default=0)),
                ('issues_reported', models.PositiveIntegerField(default=0)),
                ('issues_resolved', models.PositiveIntegerField(default=0)),
                ('institutions_reached', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
