# Generated by Django 6.1.1 on 2026-09-25 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreePlantation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField(default=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trees/')),
                ('organisation', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('planted', 'Planted'), ('verified', 'Verified'), ('growing', 'Growing'), ('survived', 'Survived')], default='planted', max_length=10)),
                ('planted_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.location')),
                ('planter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tree_plantations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-planted_on'],
            },
        ),
        migrations.CreateModel(
            name='TreeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planted', 'Planted'), ('verified', 'Verified'), ('growing', 'Growing'), ('survived', 'Survived')], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tree_checkins/')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='trees.treeplantation')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
