# Generated by Django 6.1.1 on 2026-09-25 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20)),
                ('age_group', models.CharField(blank=True, choices=[('under_18', 'Under 18'), ('18_24', '18–24'), ('25_40', '25–40'), ('41_60', '41–60'), ('60_plus', '60+')], max_length=10)),
                ('interests', models.CharField(blank=True, max_length=255)),
                ('availability', models.CharField(choices=[('weekday', 'Weekdays'), ('weekend', 'Weekends'), ('evening', 'Evenings'), ('flexible', 'Flexible')], default='flexible', max_length=10)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('consent_given', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='volunteers', to='volunteers.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
