# Generated by Django 6.1.1 on 2026-09-25 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('community_member', 'Community Member'), ('verified_volunteer', 'Verified Volunteer'), ('campaign_volunteer', 'Campaign Volunteer'), ('envirgreen_team', 'Envirgreen Team'), ('partner_org', 'Partner Organisation')], default='community_member', max_length=30)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('bio', models.CharField(blank=True, max_length=280)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
    ]
