# Generated by Django 6.1.1 on 2026-09-25 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('issues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('campaign_type', models.CharField(choices=[('river_cleanup', 'River Cleanup'), ('lake_cleanup', 'Lake Cleanup'), ('street_cleanup', 'Street Cleanup'), ('tree_plantation', 'Tree Plantation'), ('plastic_free', 'Plastic-Free Campaign'), ('school_awareness', 'School Awareness'), ('college_awareness', 'College Awareness'), ('waste_segregation', 'Waste Segregation'), ('public_awareness', 'Public Awareness'), ('urban_plantation', 'Urban Plantation')], max_length=30)),
                ('objective', models.TextField()),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='campaigns/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('goal_count', models.PositiveIntegerField(default=1, help_text='e.g. number of cleanup drives targeted')),
                ('progress_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.location')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='issues.issue')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_type', models.CharField(choices=[('volunteer', 'Volunteer'), ('financial', 'Financial'), ('material', 'Material'), ('skills', 'Skills')], max_length=20)),
                ('detail', models.CharField(blank=True, help_text="e.g. 'Can provide gloves and water'", max_length=255)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('campaign', 'user', 'support_type')},
            },
        ),
    ]
